---
name: typeracer
description: Increase Typing Speed with fun
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  provider: ^6.0.2
  socket_io_client: ^1.0.2
  socket_io: ^1.0.1
  web_socket_channel: ^2.4.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  flutter_lints: ^1.0.0
  webdev: ^3.3.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
